#!/usr/bin/env Rscript
# Shapiro-Wilk Normality Test Validation Script
# Compares R package results with p2a-core output
#
# Run with: Rscript validation/scripts/shapiro_wilk_validation.R

cat("======================================================\n")
cat("Shapiro-Wilk Test: R Validation Results\n")
cat("======================================================\n\n")

# ============================================================================
# Test Case 1: Approximately Normal Data
# ============================================================================
cat("=== Test Case 1: Approximately Normal Data ===\n")
cat("Data generated by: set.seed(42); round(rnorm(20), 4)\n\n")

x1 <- c(1.3710, -0.5647, 0.3631, 0.6329, 0.4043, -0.1062, 1.5115, -0.0947,
        2.0184, -0.0627, 1.3048, 2.2866, -1.3888, -0.2788, -0.1333, 0.6360,
        -0.2843, -2.6565, -2.4405, 1.3201)

result1 <- shapiro.test(x1)
cat(sprintf("  n = %d\n", length(x1)))
cat(sprintf("  W = %.6f\n", result1$statistic))
cat(sprintf("  p-value = %.6f\n", result1$p.value))
cat(sprintf("  Conclusion: %s\n\n",
    ifelse(result1$p.value < 0.05, "Reject normality", "Fail to reject normality")))

# ============================================================================
# Test Case 2: Small Sample (n=5)
# ============================================================================
cat("=== Test Case 2: Small Sample (n=5) ===\n\n")

x2 <- c(1.2, 2.3, 3.1, 4.5, 5.2)

result2 <- shapiro.test(x2)
cat(sprintf("  n = %d\n", length(x2)))
cat(sprintf("  W = %.6f\n", result2$statistic))
cat(sprintf("  p-value = %.6f\n", result2$p.value))
cat(sprintf("  Conclusion: %s\n\n",
    ifelse(result2$p.value < 0.05, "Reject normality", "Fail to reject normality")))

# ============================================================================
# Test Case 3: Exponential (Non-Normal) Data
# ============================================================================
cat("=== Test Case 3: Exponential (Non-Normal) Data ===\n\n")

x3 <- c(0.05, 0.12, 0.18, 0.27, 0.41, 0.58, 0.82, 1.15,
        1.63, 2.30, 3.25, 4.59, 6.49, 9.17, 12.96)

result3 <- shapiro.test(x3)
cat(sprintf("  n = %d\n", length(x3)))
cat(sprintf("  W = %.6f\n", result3$statistic))
cat(sprintf("  p-value = %.6f\n", result3$p.value))
cat(sprintf("  Conclusion: %s\n\n",
    ifelse(result3$p.value < 0.05, "Reject normality", "Fail to reject normality")))

# ============================================================================
# Test Case 4: Minimum Sample Size (n=3)
# ============================================================================
cat("=== Test Case 4: Minimum Sample Size (n=3) ===\n\n")

x4 <- c(1, 2, 3)

result4 <- shapiro.test(x4)
cat(sprintf("  n = %d\n", length(x4)))
cat(sprintf("  W = %.6f\n", result4$statistic))
cat(sprintf("  p-value = %.6f\n", result4$p.value))
cat(sprintf("  Conclusion: %s\n\n",
    ifelse(result4$p.value < 0.05, "Reject normality", "Fail to reject normality")))

# ============================================================================
# Test Case 5: Uniform Data (1:10 / 10)
# ============================================================================
cat("=== Test Case 5: Uniform Data ===\n\n")

x5 <- 1:10 / 10

result5 <- shapiro.test(x5)
cat(sprintf("  n = %d\n", length(x5)))
cat(sprintf("  W = %.6f\n", result5$statistic))
cat(sprintf("  p-value = %.6f\n", result5$p.value))
cat(sprintf("  Conclusion: %s\n\n",
    ifelse(result5$p.value < 0.05, "Reject normality", "Fail to reject normality")))

# ============================================================================
# Test Case 6: Larger Sample (n=100)
# ============================================================================
cat("=== Test Case 6: Larger Sample (n=100) ===\n\n")

set.seed(123)
x6 <- rnorm(100)

result6 <- shapiro.test(x6)
cat(sprintf("  n = %d\n", length(x6)))
cat(sprintf("  W = %.6f\n", result6$statistic))
cat(sprintf("  p-value = %.6f\n", result6$p.value))
cat(sprintf("  Conclusion: %s\n\n",
    ifelse(result6$p.value < 0.05, "Reject normality", "Fail to reject normality")))

# ============================================================================
# Summary Table
# ============================================================================
cat("======================================================\n")
cat("SUMMARY TABLE\n")
cat("======================================================\n\n")

cat(sprintf("%-25s %8s %10s %10s\n", "Test Case", "n", "W", "p-value"))
cat(sprintf("%-25s %8s %10s %10s\n", "-" , "-", "-", "-"))
cat(sprintf("%-25s %8d %10.6f %10.6f\n", "Normal (n=20)", length(x1), result1$statistic, result1$p.value))
cat(sprintf("%-25s %8d %10.6f %10.6f\n", "Small (n=5)", length(x2), result2$statistic, result2$p.value))
cat(sprintf("%-25s %8d %10.6f %10.6f\n", "Exponential (n=15)", length(x3), result3$statistic, result3$p.value))
cat(sprintf("%-25s %8d %10.6f %10.6f\n", "Minimum (n=3)", length(x4), result4$statistic, result4$p.value))
cat(sprintf("%-25s %8d %10.6f %10.6f\n", "Uniform (n=10)", length(x5), result5$statistic, result5$p.value))
cat(sprintf("%-25s %8d %10.6f %10.6f\n", "Normal (n=100)", length(x6), result6$statistic, result6$p.value))

cat("\n======================================================\n")
cat("Run Rust tests with:\n")
cat("  cargo test -p p2a-core -- shapiro --nocapture\n")
cat("======================================================\n")
