#!/usr/bin/env Rscript
# ============================================================================
# generate_paper_tables.R
# Generate all benchmark tables for the paper from comparison CSVs
#
# Reads from: performance/comparisons/r_comparison/results/
# Outputs to: paper/tables/
#
# Usage: cd paper/code && Rscript generate_paper_tables.R
# ============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
})

# Paths
script_dir <- tryCatch(
  dirname(normalizePath(sub("--file=", "", grep("--file=", commandArgs(FALSE), value = TRUE)))),
  error = function(e) getwd()
)
paper_dir <- dirname(script_dir)
project_root <- dirname(paper_dir)
results_dir <- file.path(project_root, "performance/comparisons/r_comparison/results")
tables_dir <- file.path(paper_dir, "tables")

cat("=== Generating Paper Tables from Benchmark Data ===\n")
cat("Results dir:", results_dir, "\n")
cat("Output dir:", tables_dir, "\n\n")

dir.create(tables_dir, showWarnings = FALSE, recursive = TRUE)

# ============================================================================
# Load data
# ============================================================================
speed_df <- read.csv(file.path(results_dir, "comparison_speed.csv"),
                     stringsAsFactors = FALSE)
mem_df <- read.csv(file.path(results_dir, "comparison_memory.csv"),
                   stringsAsFactors = FALSE)

matched <- speed_df %>%
  filter(!is.na(speedup_median) & is.finite(speedup_median))

largest_n <- matched %>%
  group_by(method_norm) %>%
  filter(n == max(n)) %>%
  ungroup()

cat(sprintf("Speed data: %d entries, %d matched, %d unique methods\n",
            nrow(speed_df), nrow(matched), n_distinct(matched$method_norm)))

# ============================================================================
# Helper functions
# ============================================================================
fmt_speedup <- function(x) {
  if (is.na(x) || !is.finite(x)) return("---")
  if (x > 1000) return(sprintf("$>$1000$\\times$"))
  if (x >= 100) return(sprintf("%.0f$\\times$", x))
  if (x >= 10) return(sprintf("%.1f$\\times$", x))
  return(sprintf("%.1f$\\times$", x))
}

fmt_n <- function(n) format(n, big.mark = ",")

fmt_us <- function(us) {
  if (is.na(us) || !is.finite(us)) return("---")
  if (us < 1) return("$<$1")
  return(format(round(us), big.mark = ","))
}

# ============================================================================
# Table: Benchmark Summary (tab_benchmark_summary.tex)
# ============================================================================
cat("Generating tab_benchmark_summary.tex...\n")

# Select representative methods
representative_methods <- c(
  "OLS", "OLS_HC1", "OLS_HC3", "NLS",           # Regression
  "Hausman", "Random_Effects", "Fixed_Effects", "HDFE",  # Panel
  "Logit", "Probit", "Poisson",                   # Discrete
  "Staggered_DiD", "DiD",                         # Causal
  "IV_2SLS",                                       # Econometrics
  "K-Means", "PCA", "DBSCAN",                     # ML
  "ARIMA", "MSTL",                                 # Time Series
  "Kaplan_Meier", "Cox_PH",                        # Survival
  "t_test"                                         # Stats
)

tab <- matched %>%
  filter(method_norm %in% representative_methods) %>%
  group_by(method_norm) %>%
  filter(n == max(n)) %>%
  ungroup() %>%
  arrange(module, desc(speedup_median))

# Build LaTeX table
tex <- c(
  "% Benchmark summary table -- auto-generated by generate_paper_tables.R",
  sprintf("%% Generated: %s", Sys.time()),
  "\\begin{table}[htbp]",
  "\\centering",
  paste0("\\caption{Performance benchmark results across representative methods ",
         "(median execution time). Speedup = R time / Rust time. Sample sizes ",
         "vary by method to reflect typical use cases ($n = 500$--$10{,}000$). ",
         "Methods with speedup ${>}1\\times$ are faster in Rust; methods ",
         "${<}1\\times$ are faster in R.}"),
  "\\label{tab:benchmark-full}",
  "\\renewcommand{\\arraystretch}{1.15}",
  "\\small",
  "\\begin{tabular}{llrrrr}",
  "  \\toprule",
  "Category & Method & $n$ & R ($\\mu$s) & Rust ($\\mu$s) & Speedup \\\\",
  "  \\midrule"
)

# Group by module
last_module <- ""
for (i in 1:nrow(tab)) {
  r <- tab[i, ]

  # Add midrule between modules
  if (r$module != last_module && last_module != "") {
    tex <- c(tex, "\\midrule")
  }
  last_module <- r$module

  # Clean method name for display
  method_clean <- gsub("_", " ", r$method_norm)
  method_clean <- gsub("HDFE", "HDFE (2-way)", method_clean)
  method_clean <- gsub("Kaplan Meier", "Kaplan--Meier", method_clean)
  method_clean <- gsub("OLS HC1", "OLS + HC1", method_clean)
  method_clean <- gsub("OLS HC3", "OLS + HC3", method_clean)
  method_clean <- gsub("K-Means", "K-Means ($k=3$)", method_clean)
  method_clean <- gsub("t test", "$t$-test", method_clean)
  method_clean <- gsub("IV 2SLS", "IV/2SLS", method_clean)
  method_clean <- gsub("Staggered DiD", "Staggered DiD", method_clean)
  method_clean <- gsub("Cox PH", "Cox PH", method_clean)
  method_clean <- gsub("ARIMA", "ARIMA(1,1,1)", method_clean)

  tex <- c(tex, sprintf("%s & %s & %s & %s & %s & %s \\\\",
                        r$module,
                        method_clean,
                        fmt_n(r$n),
                        fmt_us(r$r_median_us),
                        fmt_us(r$rust_median_us),
                        fmt_speedup(r$speedup_median)))
}

tex <- c(tex,
  "   \\bottomrule",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(tex, file.path(tables_dir, "tab_benchmark_summary.tex"))
cat("  Saved tab_benchmark_summary.tex\n")

# ============================================================================
# Table: Speedup Summary by Module
# ============================================================================
cat("Generating tab_speedup_by_module.tex...\n")

summary <- largest_n %>%
  group_by(module) %>%
  summarise(
    Methods = n_distinct(method_norm),
    Benchmarks = n(),
    Min = min(speedup_median),
    Median = median(speedup_median),
    Mean = mean(speedup_median),
    Max = max(speedup_median),
    .groups = "drop"
  ) %>%
  arrange(desc(Median))

tex2 <- c(
  "% Speedup summary by module -- auto-generated by generate_paper_tables.R",
  sprintf("%% Generated: %s", Sys.time()),
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Speedup summary by method category (at largest matched sample size per method). Speedup factor = R median time / Rust median time.}",
  "\\label{tab:speedup-summary}",
  "\\renewcommand{\\arraystretch}{1.15}",
  "\\small",
  "\\begin{tabular}{lrrcccc}",
  "\\toprule",
  "Module & Methods & Benchmarks & Min & Median & Mean & Max \\\\",
  "\\midrule"
)

for (i in 1:nrow(summary)) {
  r <- summary[i, ]
  tex2 <- c(tex2, sprintf("%s & %d & %d & %s & %s & %s & %s \\\\",
                          r$module, r$Methods, r$Benchmarks,
                          fmt_speedup(r$Min), fmt_speedup(r$Median),
                          fmt_speedup(r$Mean), fmt_speedup(r$Max)))
}

# Overall row
all_s <- largest_n$speedup_median
tex2 <- c(tex2,
  "\\midrule",
  sprintf("\\textbf{Overall} & \\textbf{%d} & \\textbf{%d} & %s & \\textbf{%s} & %s & %s \\\\",
          n_distinct(largest_n$method_norm), nrow(largest_n),
          fmt_speedup(min(all_s)), fmt_speedup(median(all_s)),
          fmt_speedup(mean(all_s)), fmt_speedup(max(all_s))),
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(tex2, file.path(tables_dir, "tab_speedup_by_module.tex"))
cat("  Saved tab_speedup_by_module.tex\n")

# ============================================================================
# Summary
# ============================================================================
cat("\n=== Tables Generated ===\n")
tex_files <- list.files(tables_dir, pattern = "\\.tex$")
for (f in sort(tex_files)) {
  cat(sprintf("  %s\n", f))
}
cat("\nDone.\n")
