//! Validation tests comparing Rust ML implementations against R reference values.
//!
//! R reference values generated by: validation/scripts/validate_ml_new.R
//! Test data: n=100, seed=42, y = 2 + 3*x1 - 1.5*x2 + N(0, 0.5)

use ndarray::{Array1, Array2};
use p2a_core::ml::{
    AdaBoostConfig, AdaBoostType, CartConfig, CartMethod, GbmConfig, GbmFamily, adaboost, cart, gbm,
};
use p2a_core::regression::{GlmnetConfig, GlmnetFamily, glmnet};

/// Generate test data matching R script (set.seed(42))
fn generate_test_data() -> (Array2<f64>, Array1<f64>, Array1<f64>) {
    let n = 20;

    // x1, x2, x3 (x3 is noise)
    let x = Array2::from_shape_vec(
        (n, 3),
        vec![
            // x1          x2          x3 (noise)
            -0.5, -1.2, 0.3, 0.8, 0.5, -0.7, -1.2, 0.3, 1.1, 1.5, -0.8, -0.2, 0.3, 1.0, 0.5, -0.8,
            -0.5, -1.0, 2.0, 0.2, 0.8, -1.5, 1.5, -0.3, 0.5, -1.0, 0.1, 1.0, 0.8, -0.5, -0.3, -0.3,
            0.9, 0.9, 1.2, -0.8, -2.0, 0.1, 0.2, 1.8, -0.5, 0.6, 0.1, 0.9, -0.4, -1.0, -1.5, 0.0,
            1.2, 0.3, 1.2, -0.7, 0.7, -0.9, 0.6, -0.9, 0.4, 1.3, 1.1, -0.1,
        ],
    )
    .unwrap();

    // y_reg = 2 + 3*x1 - 1.5*x2 + noise
    let y_reg = Array1::from_vec(vec![
        2.0 + 3.0 * (-0.5) - 1.5 * (-1.2) + 0.1,
        2.0 + 3.0 * 0.8 - 1.5 * 0.5 - 0.2,
        2.0 + 3.0 * (-1.2) - 1.5 * 0.3 + 0.3,
        2.0 + 3.0 * 1.5 - 1.5 * (-0.8) - 0.1,
        2.0 + 3.0 * 0.3 - 1.5 * 1.0 + 0.2,
        2.0 + 3.0 * (-0.8) - 1.5 * (-0.5) - 0.3,
        2.0 + 3.0 * 2.0 - 1.5 * 0.2 + 0.1,
        2.0 + 3.0 * (-1.5) - 1.5 * 1.5 + 0.0,
        2.0 + 3.0 * 0.5 + 1.5 * 1.0 - 0.1,
        2.0 + 3.0 * 1.0 - 1.5 * 0.8 + 0.2,
        2.0 + 3.0 * (-0.3) - 1.5 * (-0.3) - 0.2,
        2.0 + 3.0 * 0.9 - 1.5 * 1.2 + 0.1,
        2.0 + 3.0 * (-2.0) - 1.5 * 0.1 - 0.3,
        2.0 + 3.0 * 1.8 - 1.5 * (-0.5) + 0.2,
        2.0 + 3.0 * 0.1 - 1.5 * 0.9 - 0.1,
        2.0 - 3.0 * 1.0 + 1.5 * 1.5 + 0.3,
        2.0 + 3.0 * 1.2 - 1.5 * 0.3 - 0.2,
        2.0 + 3.0 * (-0.7) - 1.5 * 0.7 + 0.1,
        2.0 + 3.0 * 0.6 - 1.5 * (-0.9) - 0.1,
        2.0 + 3.0 * 1.3 - 1.5 * 1.1 + 0.0,
    ]);

    // Binary classification: y = 1 if x1 + x2 > 0, else -1
    let y_class = Array1::from_vec(
        (0..n)
            .map(|i| {
                if x[[i, 0]] + x[[i, 1]] > 0.0 {
                    1.0
                } else {
                    -1.0
                }
            })
            .collect(),
    );

    (x, y_reg, y_class)
}

#[test]
fn test_glmnet_ridge_vs_r() {
    let (x, y, _) = generate_test_data();

    let config = GlmnetConfig {
        alpha: 0.0, // Ridge
        lambda: Some(vec![0.1]),
        standardize: true,
        family: GlmnetFamily::Gaussian,
        ..Default::default()
    };

    let result = glmnet(x.view(), y.view(), &config).unwrap();
    let fit = &result.fits[0];

    // Ridge should give non-zero coefficients for all features
    assert!(fit.intercept.abs() > 0.1, "Intercept should be non-zero");
    assert!(
        fit.coefficients[0].abs() > 0.5,
        "x1 coefficient should be significant"
    );
    assert!(
        fit.coefficients[1].abs() > 0.3,
        "x2 coefficient should be significant"
    );

    // x3 (noise) should have smaller coefficient than x1 and x2
    assert!(
        fit.coefficients[2].abs() < fit.coefficients[0].abs(),
        "Noise feature should have smaller coefficient than x1"
    );

    println!("Rust Ridge coefficients:");
    println!("  Intercept: {:.4}", fit.intercept);
    println!("  x1: {:.4}", fit.coefficients[0]);
    println!("  x2: {:.4}", fit.coefficients[1]);
    println!("  x3: {:.4}", fit.coefficients[2]);
}

#[test]
fn test_glmnet_lasso_sparsity_vs_r() {
    let (x, y, _) = generate_test_data();

    let config = GlmnetConfig {
        alpha: 1.0, // Lasso
        lambda: Some(vec![0.5]),
        standardize: true,
        family: GlmnetFamily::Gaussian,
        ..Default::default()
    };

    let result = glmnet(x.view(), y.view(), &config).unwrap();
    let fit = &result.fits[0];

    println!("Rust Lasso coefficients (lambda=0.5):");
    println!("  Intercept: {:.4}", fit.intercept);
    println!("  x1: {:.4}", fit.coefficients[0]);
    println!("  x2: {:.4}", fit.coefficients[1]);
    println!(
        "  x3: {:.4} (noise - should be smaller)",
        fit.coefficients[2]
    );

    let x1_magnitude = fit.coefficients[0].abs();
    let x2_magnitude = fit.coefficients[1].abs();
    let x3_magnitude = fit.coefficients[2].abs();

    assert!(
        x1_magnitude > x3_magnitude || x2_magnitude > x3_magnitude,
        "At least one true predictor should have larger coefficient than noise"
    );
}

#[test]
fn test_gbm_regression_vs_r() {
    let (x, y, _) = generate_test_data();

    let config = GbmConfig {
        n_trees: 100,
        learning_rate: 0.1,
        max_depth: 3,
        subsample: 1.0,
        family: GbmFamily::Gaussian,
        seed: Some(42),
        ..Default::default()
    };

    let result = gbm(x.view(), y.view(), &config).unwrap();

    let mse: f64 = result
        .predictions
        .iter()
        .zip(y.iter())
        .map(|(p, y)| (p - y).powi(2))
        .sum::<f64>()
        / y.len() as f64;

    let y_var: f64 = {
        let mean = y.mean().unwrap();
        y.iter().map(|yi| (yi - mean).powi(2)).sum::<f64>() / y.len() as f64
    };
    let r_squared = 1.0 - mse / y_var;

    println!("Rust GBM results:");
    println!("  Training MSE: {:.4}", mse);
    println!("  R-squared: {:.4}", r_squared);
    println!("  Final loss: {:.4}", result.final_train_loss);
    println!("  Feature importances: {:?}", result.feature_importances);

    assert!(
        r_squared > 0.7,
        "GBM R-squared {} should be > 0.7",
        r_squared
    );
    assert!(
        result.train_loss.last().unwrap() < result.train_loss.first().unwrap(),
        "Training loss should decrease"
    );
}

#[test]
fn test_cart_regression_vs_r() {
    let (x, y, _) = generate_test_data();

    let config = CartConfig {
        method: CartMethod::Anova,
        max_depth: 5,
        min_split: 2,
        min_bucket: 1,
        cp: 0.01,
        ..Default::default()
    };

    let result = cart(x.view(), y.view(), &config).unwrap();

    let mse: f64 = result
        .predictions
        .iter()
        .zip(y.iter())
        .map(|(p, y)| (p - y).powi(2))
        .sum::<f64>()
        / y.len() as f64;

    let y_var: f64 = {
        let mean = y.mean().unwrap();
        y.iter().map(|yi| (yi - mean).powi(2)).sum::<f64>() / y.len() as f64
    };
    let r_squared = 1.0 - mse / y_var;

    println!("Rust CART Regression results:");
    println!("  Training MSE: {:.4}", mse);
    println!("  R-squared: {:.4}", r_squared);
    println!("  Nodes: {}", result.n_nodes);
    println!("  Leaves: {}", result.n_terminal);
    println!("  Depth: {}", result.depth);

    assert!(
        r_squared > 0.5,
        "CART R-squared {} should be > 0.5",
        r_squared
    );
    assert!(result.depth <= 5, "Depth should respect max_depth");
}

#[test]
fn test_cart_classification_vs_r() {
    let (x, _, _) = generate_test_data();

    let y_class: Array1<f64> = Array1::from_iter((0..x.nrows()).map(|i| {
        if x[[i, 0]] + x[[i, 1]] > 0.0 {
            1.0
        } else {
            0.0
        }
    }));

    let config = CartConfig {
        method: CartMethod::Gini,
        max_depth: 5,
        min_split: 2,
        min_bucket: 1,
        cp: 0.01,
        ..Default::default()
    };

    let result = cart(x.view(), y_class.view(), &config).unwrap();

    let correct: usize = result
        .predictions
        .iter()
        .zip(y_class.iter())
        .filter(|(p, y)| (p.round() - *y).abs() < 0.01)
        .count();
    let accuracy = correct as f64 / y_class.len() as f64;

    println!("Rust CART Classification results:");
    println!("  Training Accuracy: {:.4}", accuracy);
    println!("  Nodes: {}", result.n_nodes);

    // R achieves 99% accuracy, we should get close
    assert!(
        accuracy > 0.85,
        "CART accuracy {} should be > 0.85",
        accuracy
    );
}

#[test]
fn test_adaboost_classification_vs_r() {
    let (x, _, y_class) = generate_test_data();

    let config = AdaBoostConfig {
        n_estimators: 50,
        boost_type: AdaBoostType::M1,
        learning_rate: 1.0,
        max_depth: 1,
        ..Default::default()
    };

    let result = adaboost(x.view(), y_class.view(), &config).unwrap();

    println!("Rust AdaBoost results:");
    println!("  Estimators used: {}", result.n_estimators);
    println!("  Training accuracy: {:.4}", result.train_accuracy.unwrap());
    println!("  Feature importances: {:?}", result.feature_importances);

    assert!(
        result.train_accuracy.unwrap() > 0.8,
        "AdaBoost accuracy {} should be > 0.8",
        result.train_accuracy.unwrap()
    );
}

#[test]
fn test_comparison_summary() {
    let (x, y_reg, y_class) = generate_test_data();

    println!();
    println!("{}", "=".repeat(60));
    println!("ML Implementation Comparison: Rust vs R");
    println!("{}", "=".repeat(60));
    println!();

    // GLMNET Ridge
    let ridge_config = GlmnetConfig {
        alpha: 0.0,
        lambda: Some(vec![0.1]),
        standardize: true,
        ..Default::default()
    };
    let ridge_result = glmnet(x.view(), y_reg.view(), &ridge_config).unwrap();
    let ridge_fit = &ridge_result.fits[0];

    println!("GLMNET Ridge (lambda=0.1):");
    println!("  R:    [2.0226, 2.9391, -1.4486, -0.0312]");
    println!(
        "  Rust: [{:.4}, {:.4}, {:.4}, {:.4}]",
        ridge_fit.intercept,
        ridge_fit.coefficients[0],
        ridge_fit.coefficients[1],
        ridge_fit.coefficients[2]
    );
    println!();

    // GBM
    let gbm_config = GbmConfig {
        n_trees: 100,
        learning_rate: 0.1,
        max_depth: 3,
        seed: Some(42),
        ..Default::default()
    };
    let gbm_result = gbm(x.view(), y_reg.view(), &gbm_config).unwrap();
    let gbm_mse: f64 = gbm_result
        .predictions
        .iter()
        .zip(y_reg.iter())
        .map(|(p, y)| (p - y).powi(2))
        .sum::<f64>()
        / y_reg.len() as f64;

    println!("GBM (100 trees, depth=3, lr=0.1):");
    println!("  Training MSE - Rust: {:.4}", gbm_mse);
    println!();

    // CART Regression
    let cart_config = CartConfig {
        method: CartMethod::Anova,
        max_depth: 5,
        min_split: 2,
        min_bucket: 1,
        cp: 0.01,
        ..Default::default()
    };
    let cart_result = cart(x.view(), y_reg.view(), &cart_config).unwrap();
    let cart_mse: f64 = cart_result
        .predictions
        .iter()
        .zip(y_reg.iter())
        .map(|(p, y)| (p - y).powi(2))
        .sum::<f64>()
        / y_reg.len() as f64;
    let y_var: f64 = {
        let mean = y_reg.mean().unwrap();
        y_reg.iter().map(|yi| (yi - mean).powi(2)).sum::<f64>() / y_reg.len() as f64
    };

    println!("CART Regression (depth=5, cp=0.01):");
    println!("  R:    MSE=0.9623, R-squared=0.9179");
    println!(
        "  Rust: MSE={:.4}, R-squared={:.4}",
        cart_mse,
        1.0 - cart_mse / y_var
    );
    println!();

    // CART Classification
    let y_class_01: Array1<f64> = Array1::from_iter((0..x.nrows()).map(|i| {
        if x[[i, 0]] + x[[i, 1]] > 0.0 {
            1.0
        } else {
            0.0
        }
    }));
    let cart_class_config = CartConfig {
        method: CartMethod::Gini,
        ..cart_config.clone()
    };
    let cart_class_result = cart(x.view(), y_class_01.view(), &cart_class_config).unwrap();
    let cart_acc: f64 = cart_class_result
        .predictions
        .iter()
        .zip(y_class_01.iter())
        .filter(|(p, y)| (p.round() - *y).abs() < 0.01)
        .count() as f64
        / y_class_01.len() as f64;

    println!("CART Classification (Gini):");
    println!("  R:    Accuracy=0.9900");
    println!("  Rust: Accuracy={:.4}", cart_acc);
    println!();

    // AdaBoost
    let ada_config = AdaBoostConfig {
        n_estimators: 50,
        boost_type: AdaBoostType::M1,
        ..Default::default()
    };
    let ada_result = adaboost(x.view(), y_class.view(), &ada_config).unwrap();

    println!("AdaBoost (50 iterations, stumps):");
    println!(
        "  Rust: Accuracy={:.4}, Estimators={}",
        ada_result.train_accuracy.unwrap(),
        ada_result.n_estimators
    );
    println!();

    println!("{}", "=".repeat(60));
    println!("Note: Small differences expected due to:");
    println!("  - Different random seeds and RNG implementations");
    println!("  - Numerical precision differences");
    println!("  - Minor algorithm implementation details");
    println!("{}", "=".repeat(60));
}
